#!/bin/sh
echo "Install crontab"
crontab ~/current/crontab

echo "Make output directory"
mkdir -p ~/output

echo "Run script to get updated information"
/home/dotcloud/env/bin/python /home/dotcloud/current/pypi_mirrors.py > /home/dotcloud/output/index.html